### ISSUE TITLE
Suggestion: Update package version on PyPI

### ISSUE THREAD

**Issue by Altoria** [estin/django-admin-data-from-external-service#1]
Hi, I recently came across an issue with `django-admin-data-from-external-service` package when using it with the latest version of Django (Django 4).

But I checked the code on the `master` branch and it works fine with it. 

Can you update the package version on PyPI so that it works well with the latest version of Django?

Thanks for maintaining this package.

**Comment by estin** [comment]
done

**Comment by Altoria** [comment]
Great! :D
